### ISSUE TITLE
Unicode is not supported in python3

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-bigquery-py#13]

**Comment by roll** [comment]
@pwalsh 
@vitorbaptista 
Something strange goes here with python3 version. May be bigquery driver bug. I hope on the next iteration we will brainstrom it. So for now it's just backlogged.

**Comment by pwalsh** [comment]
Hey.
1. Does the BigQuery driver actually support Py3?
2. I'm not sure based, on the use of `six`, what type of problems can arise. As I said earlier on, my personal preference is not to use six, enforce unicode everywhere except the boundary of the app, and in general follow everything in https://docs.python.org/3/howto/pyporting.html, as I have done in GoodTables etc. I'll have to learn what magic six invokes to be of more help.

**Comment by roll** [comment]
Thanks!
1. It's decraled - https://developers.google.com/api-client-library/python/apis/bigquery/v2
2.  Sorry I didn't highlight the problem - https://github.com/okfn/jsontableschema-bigquery-py/blob/master/jtsbq/storage.py#L246-L292 - this code doesn't use `six` and fails with:

```
Traceback (most recent call last):
  File "examples/testing.py", line 51, in <module>
    pprint(run(dataset, prefix, table, schema, data))
  File "./examples/base.py", line 36, in run
    storage.write(table, data)
  File "./jtsbq/storage.py", line 291, in write
    media_body=media_body).execute()
  File "/home/roll/projects/jsontableschema-bigquery-py/venv/local/lib/python3.4/site-packages/oauth2client/util.py", line 140, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/roll/projects/jsontableschema-bigquery-py/venv/local/lib/python3.4/site-packages/googleapiclient/http.py", line 722, in execute
    body=self.body, headers=self.headers)
  File "/home/roll/projects/jsontableschema-bigquery-py/venv/local/lib/python3.4/site-packages/oauth2client/client.py", line 596, in new_request
    redirections, connection_type)
  File "/home/roll/projects/jsontableschema-bigquery-py/venv/local/lib/python3.4/site-packages/httplib2/__init__.py", line 1314, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/roll/projects/jsontableschema-bigquery-py/venv/local/lib/python3.4/site-packages/httplib2/__init__.py", line 1064, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/roll/projects/jsontableschema-bigquery-py/venv/local/lib/python3.4/site-packages/httplib2/__init__.py", line 988, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in _send_request
    body = body.encode('iso-8859-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 478-486: ordinal not in range(256)
```

I didn't have time to dive so deep - I just don't understand why it's trying to encode it to `latin-1`. Input for request seems to be correct - dict as body and bytes wrapped in MediaIOBaseUpload as media_body. 'UTF-8' is default for bigquery - so we don't need to set it in `body.configuration`.

**Comment by roll** [comment]
It looks there are good news about this issue - seemed to be fixed in BigQuery driver because `testsuite-py` now is able to push/pull `country-list` (with unicode chars) datapackage to BigQuery - https://travis-ci.org/frictionlessdata/testsuite-py/jobs/118977271.

FIXED
